# Generated by Django 2.2.4 on 2019-09-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomImpuesto', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUnidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(default=55, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Impuesto')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Unidad')),
            ],
        ),
    ]
