# Generated by Django 2.2.4 on 2019-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclie', models.IntegerField()),
                ('nombres', models.CharField(blank=True, max_length=40)),
                ('ID', models.IntegerField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('telefono', models.IntegerField(default=222222)),
            ],
        ),
    ]
