# Generated by Django 2.2.4 on 2019-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('clients', '0003_auto_20190913_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaclient',
            name='producto',
            field=models.ManyToManyField(to='inventario.Producto'),
        ),
    ]
