# Generated by Django 2.2.4 on 2019-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20190913_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaclient',
            name='producto',
        ),
        migrations.AddField(
            model_name='facturaclient',
            name='pedido',
            field=models.ManyToManyField(to='clients.pedidoCliente'),
        ),
    ]
