# Generated by Django 2.2.4 on 2019-09-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('idproveedor', models.IntegerField(default=30, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=20)),
                ('vendedor', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='facturaProveedor',
            fields=[
                ('factura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('vence', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
        ),
    ]
