# Generated by Django 2.2.4 on 2019-09-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20190914_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
