# Generated by Django 2.2.4 on 2019-09-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_auto_20190914_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='vence',
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
