# Generated by Django 2.2.4 on 2019-09-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0005_auto_20190914_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facturaProveedor',
        ),
    ]
