# Generated by Django 2.2.4 on 2019-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_delete_facturaproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='idproveedor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
