# Generated by Django 2.2.4 on 2019-09-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0007_auto_20190914_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaProveedor',
            fields=[
                ('factura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('vence', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
        ),
    ]
